plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kalab.chess.stockfishengine'
    compileSdk 35

    defaultConfig {
        applicationId "com.kalab.chess.stockfishengine"
        minSdk 21
        targetSdk 35
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
            keepDebugSymbols += "**/libstockfish.so"
        }
    }

    signingConfigs {
        release {
            if (System.getenv("SIGNING_KEY_FILE") != null) {
                storeFile file(System.getenv("SIGNING_KEY_FILE"))
                storePassword System.getenv("KEYSTORE_PASSWORD")
                keyAlias System.getenv("KEY_ALIAS")
                keyPassword System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (System.getenv("SIGNING_KEY_FILE") != null) {
                signingConfig signingConfigs.release
            }
        }
        debug {
            if (System.getenv("SIGNING_KEY_FILE") != null) {
                signingConfig signingConfigs.release
            }
        }
    }
}

dependencies {
    implementation project(':chessEngineSupportLibrary')
}
